.TH GCLIENT 1
.SH NAME
gclient \- connect to a gserver
.SH SYNOPSIS
.B gclient
\fIip\fB:\fIport\fR
.IR name
.SH DESCRIPTION
.B gclient
Connects to the gserver at \fIip\fB:\fIport\fR.  The gclient will identify itself as \fIname\fR.
.SH EXAMPLES
.TP
gclient 127.0.0.1:11777 TheLegend27
.SH SEE ALSO
gserver(1)
.SH AUTHOR
Gianluca Tarquinio
